//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int UserId { get; set; }
        public Nullable<int> IdCounterparty { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Direction { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
    }
}
